# permissions for end users to edit redis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-editor-role
rules:
- apiGroups:
  - cache.ranryl.io.ranryl.com
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.ranryl.io.ranryl.com
  resources:
  - redis/status
  verbs:
  - get
