# permissions for end users to view redisreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisreplication-viewer-role
rules:
- apiGroups:
  - cache.ranryl.io.ranryl.com
  resources:
  - redisreplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.ranryl.io.ranryl.com
  resources:
  - redisreplications/status
  verbs:
  - get
