# permissions for end users to view redisreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisreplication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-operator
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisreplication-viewer-role
rules:
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisreplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisreplications/status
  verbs:
  - get
