---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - update
- apiGroups:
  - ""
  resources:
  - serivces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.ranryl.io
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.ranryl.io
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisreplications/finalizers
  verbs:
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redisreplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.ranryl.io
  resources:
  - redissentinels/finalizers
  verbs:
  - update
- apiGroups:
  - redis.ranryl.io
  resources:
  - redissentinels/status
  verbs:
  - get
  - patch
  - update
