apiVersion: cache.ranryl.io.ranryl.com/v1beta1
kind: RedisCluster
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: rediscluster-sample
spec:
  # TODO(user): Add fields here
