apiVersion: redis.ranryl.io/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-sample
spec:
  image: "redis:7.2.4"
  port: 6379
