apiVersion: redis.ranryl.io/v1beta1
kind: RedisReplication
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisreplication-sample
spec:
  image: "redis:7.2.4"
  masterReplica: 1
  slaveReplica: 2
  port: 6379
  configPath: "/usr/local/etc/redis/redis.conf"
  slaveConfig: |
    bind * -::*
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    pidfile /var/run/redis_6379.pid
    #replicaof 127.0.0.1 6379

